name:                hMPC
version:             0.1.0.2
github:              "nickvgils/hMPC"
license:             BSD3
author:              "Nick van Gils"
maintainer:          "nick.vangils@hotmail.com"
copyright:           "2024 Nick van Gils"
category:             "Cryptography"
data-dir:             demos/data
data-files:           id3/*

extra-source-files:
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Multiparty Computation in Haskell
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  hMPC is a Haskell package for secure multiparty computation (MPC).
  .
  hMPC provides a runtime for performing computations on secret-shared values,
  where parties interact by exchanging messages via peer-to-peer connections.
  The hMPC protocols are based on Shamir's threshold secret sharing scheme
  and withstand passive adversaries controlling less than half of the parties.
  .
  Secure integer arithmetic is supported for parameterized
  number ranges, including support for comparison operations.
  Secure finite field arithmetic is supported.
  .
  The above operations are all available via Haskell's operator overloading.
  .
  Secure drop-in replacements for lots of Haskell built-in functions, such as
  'all', 'sum', 'min', 'max' are provided, mimicking the Haskell
  APIs as much as possible. Further operations for container datatypes holding
  secret-shared data items are provided as well (e.g., matrix-vector operations
  like secure dot products).

dependencies:
- base >= 4.7 && < 5
- network >= 3.1.2.7 && < 3.3
- optparse-applicative >= 0.16.1.0 && < 0.19
- process >= 1.6.13 && < 1.7
- random >= 1.2.1 && < 1.3
- containers >= 0.6.4 && < 0.8
- mtl >= 2.2.2 && < 2.4
- hgmp >= 0.1.2 && < 0.2
- bytestring >= 0.10.12 && < 0.13
- cereal >= 0.5.8 && < 0.6
- vector >= 0.12.3.1 && < 0.14
- hashable >= 1.3.5.0 && < 1.6
- split >= 0.2.3.4 && < 0.3
- binary >= 0.8.8 && < 0.9
- stm >= 2.5.0 && < 2.6
- lens >= 5.0.1 && < 5.4
- time >= 1.9.3 && < 1.15
- hslogger >= 1.3.1 && < 1.4

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: app
  exposed-modules:
    - Shamir
    - FinFields
    - Runtime
    - SecTypes
    - Types
    - Asyncoro
    - Parser
    - Hgmp
    - Paths_hMPC


executables:
  # demos
  id3gini:
    main:                Id3gini.hs
    source-dirs:         demos
    ghc-options:
    - -main-is Id3gini
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hMPC

tests:
  test-hMPC:
    main:                TestMain.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hMPC
    - HUnit >= 1.6.2.0
